### ISSUE TITLE
Update to FMI3.x?

### ISSUE THREAD

**Issue by lilumdaru** [OpenSimulationInterface/osi-sensor-model-packaging#105]
#### Describe the problem
The Input into OSMP FMU is of binary format. FMI 2.0 doesn't allow this directly, so a pointer-workaround has been created.

#### Describe your research
By now FMI3.1 is released and a binary type of input was introduced. ( https://fmi-standard.org/docs/3.0.1/#fmi-whats-new )

#### Ask your question
Are there any plans to update the OSMP FMUs to use FMI3.x?

**Comment by chrbertsch** [comment]
@pmai : can you comment on plans for FMI 3.0 support, or is there already a prototype available?
see also https://stackoverflow.com/questions/77660478/fmu-gives-the-thread-tried-to-read-from-or-write-to-a-virtual-address-for-which?
