### ISSUE TITLE
File already exists in database: osi_version.proto | Issues with OSMP FMU run with OpenMCX in Ubuntu 18.04

### ISSUE THREAD

**Issue by levanthanh3005** [OpenSimulationInterface/osi-sensor-model-packaging#112]
Hi,
I tried to generate FMU from OSMPDummySensor and OSMPDummySource,
Then create a SSD file to run with OpenMCX,
But the error always happens
`
[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: osi_version.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):    
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
`

It still happens even when build with static mode

`cd build && cmake -DCMAKE_CXX_FLAGS="-fPIC" .. && cmake --build .`

I run all steps in Ubuntu 18.04, and already tried with protobuf 3.0.0, 3.6.1, 3.4.0.

Besides OpenMCX, I also test with FMPy to run ssp, but the error is still the same,
It seems this error only happens in Ubuntu, in Window with ModelConnect, everything works fines

Could you please take a look @pmai @ClemensLinnhoff @PhRosenberger 

[SystemStructure.openmcx.ssd.txt](https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/files/15332041/SystemStructure.openmcx.ssd.txt)

**Comment by ClemensLinnhoff** [comment]
This error usually occurs if protobuf is build for dynamic linking. Did you install protobuf according to the recommended instructions for static linking [here](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/interface/setup/installing_prerequisites.html#_linux)?

**Comment by levanthanh3005** [comment]
Thank you @ClemensLinnhoff a lot, 
I miss `--disable-shared`, I test with a first simulation and it is fine now
