### ISSUE TITLE
linker problems

### ISSUE THREAD

**Issue by florianmauch** [OpenSimulationInterface/osi-sensor-model-packaging#13]
I've just tried to compile the project and get the following error:

unresolved external symbol "private: static bool google:protobuf::io::CodedOutputStream::deafult_serialization_deterministic_"

I've sperately built protobuf from the current master out of the protobuf repository (3.2). open_simulation_interface and open_simulation_interface_pic also build just fine. Are there any special build settings I have to use when building protobuf?

Any ideas on this?

Thanks already,
Florian

**Comment by pmai** [comment]
Hmmm, seems strange, I will look into this. Could you test against protobuf Release 2.6.1 (i.e. the last proto2 release), which is the version we are using in the travis CI build, and report if this also causes this problem for you?

**Comment by pmai** [comment]
I've not been able to reproduce this issue and have received no other reports of a problem like this, so will close.
