### ISSUE TITLE
SensorViewConfiguration

### ISSUE THREAD

**Issue by ghost** [OpenSimulationInterface/osi-sensor-model-packaging#37]
I was wondering where the definition for the exchange of the configuration message is handled? Because the framework integrating the FMU would like to ask the configuration from the sensor FMU and store this information in SensorView?

**Comment by pmai** [comment]
The example FMUs currently do not include this optional part of the spec (i.e. FMUs do not have to provide configuration data, in that case the actual SensorView configuration must be manually handled in the simulation environment), however I plan on adding a sample implementation prior to 1.0.0 release.

The workflow is really: FMU offers a `OSMPSensorViewInConfigRequest` calculatedParameter that the simulation environment queries during initmode, then sets the `OSMPSensorViewInConfig` parameter with what it can support of this request (ideally identical, but can leave out stuff it does not support). Then init mode is exited and simulation can proceed.

In the case that the FMU's desired input configuration depends on other parameters of the FMU (e.g. a generic sensor model which has parameters to change the FoV of the sensor), the calculatedParameter `OSMPSensorViewInConfigRequest` will depend on those parameters, hence the simulation environment must set those prior to reading the `OSMPSensorViewInConfigRequest` parameter.
