### ISSUE TITLE
Is SensorDataInput from V0.2.1 still valid?

### ISSUE THREAD

**Issue by PhRosenberger** [OpenSimulationInterface/osi-sensor-model-packaging#41]
We would like to build a logical model with SensorData in and SensorData out. Therefore, we need a description on the input of such logical models (as they are now called in OSI packaging 1.0.0). We assume it to be the same as in the older OSI version, but it needs to be defined.

**Comment by pmai** [comment]
Hmmm, are you missing something that is not in #40 ?

**Comment by PhRosenberger** [comment]
We will have a look.

**Comment by PhRosenberger** [comment]
We are not missing anything, so issue can be closed.
