### ISSUE TITLE
Link to documentation in README is broken

### ISSUE THREAD

**Issue by tpajenkamp-dspace** [OpenSimulationInterface/osi-sensor-model-packaging#50]
#### Describe the bug
The link in README.MD to the official documentation is dead.
The link refers to `https://opensimulationinterface.github.io/osi-documentation/osi-model-packaging/README.html` which no longer exists. Should it be https://opensimulationinterface.github.io/osi-documentation/osi-sensor-model-packaging/README.html or https://opensimulationinterface.github.io/osi-documentation/osi-sensor-model-packaging/doc/description.html?

#### Describe how to reproduce the bug
1. Go to the main code page of the repository
2. Click on the link 'official documentation' in the first paragraph
3. error 404

#### Describe the expected behavior
The official documentation page opens.

**Comment by vkresch** [comment]
@tpajenkamp-dspace thanks for the bug report. Issue is resolved [here](https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/pull/51).
