### ISSUE TITLE
Unable to build OSMPDummySource example

### ISSUE THREAD

**Issue by vibhoraggarwal** [OpenSimulationInterface/osi-sensor-model-packaging#55]
#### Description

I generated the [OSMPDummySource example](https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/tree/master/examples/OSMPDummySource) using cmake in Windows, but while building it up I am facing linking error. I can’t figure out what I am doing wrong. Do you have any suggestion, or might have faced similar problem in the past?

#### Already installed requisites
1. Protobuf v2.6.1 (x86 Release)
2. Microsoft Visual Studio 12 2013
3. osi libraries

#### Already tried
1. I ran following commands from build folder:

   `cmake .. -G "Visual Studio 12 2013" -DCMAKE_INSTALL_PREFIX=C:/Libraries/OSMPDummySource`

   `cmake --build .`

   I received the following error at first:

   `LINK : fatal error LNK1104: cannot open file 'open_simulation_interface_pic.lib' [C:\git\osi-sensor-model-packaging\exa
mples\OSMPDummySource\build\OSMPDummySource.vcxproj]`

2. Then I included the path of `.lib` file in my `paths` environment variable, as per the following discussion: https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1104?view=vs-2019 

    a. But, I still had to copy paste the .lib file in my local folder.
       I still am receiving the following error:

```
open_simulation_interface_pic.lib(osi_version.pb.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in OSMPDummySource.obj [C:\git\osi-sensor-model-packaging\examples\OSMPDummySource\build\OSMPDummySource.vcxproj]open_simulation_interface_pic.lib(osi_version.pb.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in OSMPDummySource.obj [C:\git\osi-sensor-model-packaging\examples\OSMPDummySource\build\OSMPDummySource.vcxproj]open_simulation_interface_pic.lib(osi_common.pb.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in OSMPDummySource.obj [C:\git\osi-sensor-model-packaging\examples\OSMPDummySource\build\OSMPDummySource.vcxproj] 
```

**Comment by pmai** [comment]
Did you start the configuration/build of the examples at the top of the tree? I.e. it seems like you created the build folder inside the OSMPDummySource folder; building of individual examples without the common setup in examples/CMakefiles is not supported (exactly for the reasons of incompatible libraries causing problems).

So in examples, create a build folder and run cmake from there, which will ensure that a matching OSI lib is also generated and used:

```
cd examples
mkdir build
cd build
cmake .. -G "Visual Studio 12 2013"
cmake --build .
```

This will build and include the matching OSI libraries from the open-simulation-interface directory at top level (populated by the submodule with git submodule update --init). If you want to build against a different version of OSI, you would just place that source at the same level.

The linker error you were getting indicates that the OSI lib you were linking against was built for Release, whereas you are building for Debug. By building everything in one, these problems cannot happen.

**Comment by vibhoraggarwal** [comment]
@pmai Thanks, I was indeed building the libraries from individual example folder. 

I had built from the `example/build` as well. But, was additionally building it from the individual example. Thanks again. 

#### Just for somebody who follows this issue:

I had to use `cmake --build . --config Release` instead of `cmake --build .` because of my (other) libraries built in Release configuration.
