### ISSUE TITLE
File already exists in database (Windows)

### ISSUE THREAD

**Issue by sebastian-wolter-itk** [OpenSimulationInterface/osi-sensor-model-packaging#87]
Hi, i'm currently trying to use a packed OSI-Sensor Model as FMU (DummySensor) and execute it via C++ (via FMI4CPP or FMI++) and deserialize (in the same application) under Windows:
It seems that there is an issue, if same protobuf-compiled code (=OSI Library) is shared between applications/dll

- Main Application: links to open_simulation_interface.dll
- Sensor Model FMU: also links to open_simulation_interface.dll

(if i do not include osi headers, it works)
![grafik](https://user-images.githubusercontent.com/50950633/195097497-13eb2c1c-58dd-41e7-a69c-c5efe44e96aa.png)
Also splitting the deserialization part into a seperate DLL does not solve the problem.
seems to be related to: https://stackoverflow.com/questions/37051635/several-shared-object-using-same-proto-leading-the-the-error-file-already-exist
(but did not solve the problem)

Is anyone also experience that kind of problem in C++ Environment?
Shouldn't it be a normal use case in a testing environment e.g. to have a multiple FMU running, e.g. one produces SensorData and one consumes SensorData?

**Comment by pmai** [comment]
This is a limitation of ProtoBuf. This is why the example models default to static linking of the OSI library, which solves the problem on Windows, and is also the recommended way to package FMUs: They should have minimal external dependencies, in order to ensure maximum portability.

With regard to OSI this is also better, since it allows multiple versions of OSI to coexist (consider a model using a newer/older minor release than the simulation of other models).

BTW for Linux also the proper linker flags need to be used to restrict symbol lookup to the shared object to avoid global lookups...

**Comment by sebastian-wolter-itk** [comment]
with static linking of libprotobuf.lib and open_simulation_interface_static.lib i was able to get it running. Thanks for the quick help.

**Comment by ClemensLinnhoff** [comment]
I am having the same problem in Linux. I just cloned the packaging repository twice and built the DummySource in one and the DummySensor in the other (to simulate getting two FMUs from different sources). Using OpenMCx to co-simulate the source and sensor FMU produces the same error. `LINK_WITH_SHARED_OSI` is set to `OFF` for both FMUs, as is the default.

@pmai you mentioned "proper linker flags" that need to be set in Linux. Could you elaborate on that?

**Comment by PhRosenberger** [comment]
@jruebsam could you explain your solution to the linker problem on Linux / Windows / protobuf-compiler here, as well?

**Comment by PhRosenberger** [comment]
Related: https://github.com/OpenSimulationInterface/open-simulation-interface/issues/592

**Comment by pmai** [comment]
See https://github.com/OpenSimulationInterface/open-simulation-interface/issues/592#issuecomment-1424009438

The relevant linker flag is `-Bsymbolic`, i.e. `-Wl,-Bsymbolic` on the gcc command-line.

**Comment by jruebsam** [comment]
@PhRosenberger: see https://github.com/OpenSimulationInterface/open-simulation-interface/issues/592#issuecomment-1433054913

**Comment by PhRosenberger** [comment]
Let's continue the discussion for the [README PR](https://github.com/OpenSimulationInterface/open-simulation-interface/pull/715) and the [Docu PR](https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/pull/93).
