### ISSUE TITLE
Usage of DCP in Network Proxy

### ISSUE THREAD

**Issue by jdsika** [OpenSimulationInterface/osi-sensor-model-packaging#96]
I was wondering if the Network Proxy example should follow the [DCP specification](https://dcp-standard.org/dcp/)? Maybe we could organize a quick call about this topic and Pierre could give some insights into DCP? I assume that you have been involved here?

It could be a receiver/sender FMU component also used in OpenMSL?

Best regards
Carlo

**Comment by ClemensLinnhoff** [comment]
I don't know anything about DCP. So a quick call would probably be best.
We might also want to talk about [DDS](https://www.dds-foundation.org/) then. We implemented DDS with OSI and it works quite well (without the need of a co-simulation master).

**Comment by pmai** [comment]
DCP really sits at a level on top of FMI, i.e. one would use a DCP capable implementation to import an FMU and remote it, not necessarily embed a DCP implementation inside an FMU (which, depending on the mode of DCP being used might not even be possible). The DCP specification is also rather complex for the little it achieves in this regard (simple co-simulation), so the question for me would be what the use cases are that people have in mind. Really, one should avoid distributed co-simulation as far as one can (heavy performance impact, etc.), so when one has to use it, the details of what is advisable really depend on the specific use cases.

That being said, the network proxy example is just a toy example like the DummySensor, to show how in principle something can be done, not an industrial strength building block for others to use, so anything that makes this more complex and specific really seems like not a good idea.

**Comment by ClemensLinnhoff** [comment]
Is there more need for discussion or can we close this issue?

**Comment by jdsika** [comment]
Decision: Discard the idea of playing around with DCO
